# Generated by Django 5.0.6 on 2024-09-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('situacao', models.IntegerField()),
                ('fotos', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('user_ip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
