# Generated by Django 5.0.6 on 2024-09-22 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0002_alter_denuncia_descricao_alter_denuncia_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='situacao',
        ),
    ]
