# Generated by Django 5.0.6 on 2024-09-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_remove_denuncia_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
